<?php

return [
    'pt' => [
        [
            'slug' => 'gestao-desempenho',
            'title' => 'Gestão de Desempenho',
            'short' => 'Sistemas claros de objectivos, feedback, avaliação e desenvolvimento para transformar esforço em resultados.',
            'value' => 'Um bom sistema de desempenho cria foco, reduz subjectividade e ajuda líderes e equipas a conversarem sobre resultados com evidências.',
            'audience' => 'Directores, gestores de RH e equipas de liderança que querem alinhar contribuição individual com prioridades do negócio.',
            'alerts' => ['Objectivos pouco claros ou mudam sem critério.', 'Avaliações feitas apenas no fim do ano.', 'Feedback irregular e pouco accionável.', 'Baixa ligação entre desempenho, desenvolvimento e recompensas.'],
            'checklist' => ['Os objectivos individuais estão ligados aos objectivos da empresa?', 'Há ciclos regulares de feedback e acompanhamento?', 'Os critérios de avaliação são compreendidos por gestores e colaboradores?', 'Os resultados geram planos de desenvolvimento concretos?'],
            'deliverables' => ['Modelo de gestão de desempenho', 'Matriz de objectivos e indicadores', 'Instrumentos de avaliação', 'Guião para feedback e calibração'],
        ],
        [
            'slug' => 'carreira-sucessao',
            'title' => 'Planos de Carreira e Sucessão',
            'short' => 'Percursos de evolução, mapas de sucessão e preparação de talentos críticos para garantir continuidade.',
            'value' => 'Carreira e sucessão bem estruturadas ajudam a reter conhecimento, preparar liderança e mostrar caminhos reais de crescimento.',
            'audience' => 'Organizações que querem reduzir dependência de pessoas-chave e tornar o crescimento interno mais visível.',
            'alerts' => ['Promoções sem critérios consistentes.', 'Talentos críticos sem plano de desenvolvimento.', 'Líderes preparados apenas quando surge uma vaga.', 'Colaboradores sem clareza sobre próximos passos.'],
            'checklist' => ['As funções críticas estão identificadas?', 'Existe mapa de sucessores por área?', 'Os critérios de progressão são transparentes?', 'Há planos de desenvolvimento para potenciais sucessores?'],
            'deliverables' => ['Arquitectura de carreira', 'Mapa de sucessão', 'Critérios de progressão', 'Planos individuais de desenvolvimento'],
        ],
        [
            'slug' => 'avaliacao-classificacao-cargos',
            'title' => 'Avaliação e Classificação de Cargos',
            'short' => 'Arquitectura de cargos, descrições de funções e enquadramento consistente para decisões justas.',
            'value' => 'A avaliação de cargos cria base técnica para remuneração, estrutura, recrutamento, desenvolvimento e gestão de expectativas.',
            'audience' => 'Empresas que cresceram, mudaram funções ou precisam organizar responsabilidades e níveis com maior rigor.',
            'alerts' => ['Funções com responsabilidades sobrepostas.', 'Títulos diferentes para trabalhos semelhantes.', 'Dificuldade em justificar níveis e salários.', 'Descrições de funções desactualizadas.'],
            'checklist' => ['As descrições de funções reflectem o trabalho real?', 'Os níveis de responsabilidade estão diferenciados?', 'Há critérios técnicos para classificar cargos?', 'A estrutura apoia decisões de remuneração e carreira?'],
            'deliverables' => ['Descrições de funções', 'Matriz de avaliação de cargos', 'Estrutura de níveis', 'Relatório de enquadramento'],
        ],
        [
            'slug' => 'perfil-comportamental',
            'title' => 'Mapeamento do Perfil Comportamental',
            'short' => 'Perfis baseados em evidências para melhorar selecção, composição de equipas e desenvolvimento individual.',
            'value' => 'Conhecer padrões comportamentais ajuda a tomar decisões melhores sobre contratação, liderança, equipas e desenvolvimento.',
            'audience' => 'Equipas que precisam melhorar colaboração, recrutamento, liderança ou adaptação de pessoas às funções.',
            'alerts' => ['Contratações tecnicamente boas mas com baixo encaixe comportamental.', 'Conflitos recorrentes entre equipas.', 'Dificuldade em adaptar estilos de liderança.', 'Planos de desenvolvimento muito genéricos.'],
            'checklist' => ['Os perfis comportamentais são usados com critério e ética?', 'As competências da função estão bem definidas?', 'A equipa conhece os seus estilos de trabalho?', 'Os resultados geram acções práticas de desenvolvimento?'],
            'deliverables' => ['Mapas comportamentais', 'Relatórios individuais e de equipa', 'Guiões de entrevista', 'Recomendações de desenvolvimento'],
        ],
        [
            'slug' => 'recrutamento-seleccao',
            'title' => 'Recrutamento e Selecção',
            'short' => 'Processos de recrutamento rigorosos, alinhados à função, cultura e necessidades reais do negócio.',
            'value' => 'Recrutar bem não é apenas preencher vagas; é reduzir risco, acelerar adaptação e proteger a cultura da organização.',
            'audience' => 'Empresas que precisam atrair, avaliar e seleccionar talentos com consistência e velocidade responsável.',
            'alerts' => ['Contratações baseadas apenas em CV e entrevista informal.', 'Rotatividade alta nos primeiros meses.', 'Processos longos sem comunicação clara.', 'Gestores desalinhados sobre o perfil ideal.'],
            'checklist' => ['O perfil da vaga tem critérios técnicos e comportamentais?', 'A triagem usa evidências objectivas?', 'As entrevistas são estruturadas?', 'Existe plano de integração após contratação?'],
            'deliverables' => ['Perfil da vaga', 'Shortlist qualificada', 'Relatórios de avaliação', 'Recomendações de integração'],
        ],
        [
            'slug' => 'politicas-procedimentos',
            'title' => 'Políticas e Procedimentos',
            'short' => 'Políticas de RH e procedimentos operacionais claros, práticos e alinhados à conformidade legal.',
            'value' => 'Boas políticas dão previsibilidade, protegem a empresa e ajudam gestores a decidir com justiça e consistência.',
            'audience' => 'Organizações que precisam formalizar regras, reduzir improviso e alinhar práticas internas.',
            'alerts' => ['Decisões diferentes para casos semelhantes.', 'Procedimentos conhecidos apenas por algumas pessoas.', 'Documentos longos que ninguém usa.', 'Riscos legais por práticas pouco claras.'],
            'checklist' => ['As políticas estão actualizadas e acessíveis?', 'Os procedimentos são simples de executar?', 'Gestores sabem aplicar as regras?', 'Há alinhamento entre política, lei e cultura?'],
            'deliverables' => ['Manual de políticas de RH', 'Fluxos de procedimento', 'Modelos e formulários', 'Sessões de implementação'],
        ],
        [
            'slug' => 'remuneracao-beneficios',
            'title' => 'Remuneração e Benefícios',
            'short' => 'Modelos salariais e benefícios equilibrados entre competitividade, sustentabilidade e equidade interna.',
            'value' => 'Uma política remuneratória clara ajuda a atrair, reter e reconhecer talento sem perder controlo financeiro.',
            'audience' => 'Empresas que querem organizar salários, benefícios, bandas e critérios de evolução remuneratória.',
            'alerts' => ['Salários definidos por negociação individual sem estrutura.', 'Percepção de injustiça interna.', 'Benefícios pouco valorizados pelos colaboradores.', 'Dificuldade em reter perfis críticos.'],
            'checklist' => ['Existe estrutura de bandas salariais?', 'A política equilibra mercado e capacidade financeira?', 'Os critérios de revisão são claros?', 'Os benefícios respondem às necessidades da equipa?'],
            'deliverables' => ['Diagnóstico remuneratório', 'Estrutura de bandas', 'Política de benefícios', 'Recomendações de implementação'],
        ],
        [
            'slug' => 'formacao-desenvolvimento',
            'title' => 'Formação e Desenvolvimento',
            'short' => 'Programas de aprendizagem desenhados para competências reais, aplicação prática e impacto mensurável.',
            'value' => 'Formação só cria valor quando parte de necessidades concretas e termina com mudança observável no trabalho.',
            'audience' => 'Organizações que precisam desenvolver liderança, competências técnicas, comunicação, cultura ou desempenho.',
            'alerts' => ['Formações escolhidas sem diagnóstico.', 'Participantes motivados no dia, mas sem aplicação depois.', 'Ausência de indicadores de aprendizagem.', 'Planos de desenvolvimento pouco ligados ao negócio.'],
            'checklist' => ['A necessidade de formação está bem diagnosticada?', 'Os objectivos de aprendizagem são mensuráveis?', 'Há aplicação prática após a formação?', 'O impacto é acompanhado pelos gestores?'],
            'deliverables' => ['Diagnóstico de necessidades', 'Plano de formação', 'Materiais de aprendizagem', 'Avaliação de impacto'],
        ],
        [
            'slug' => 'assessoria-outsourcing-rh',
            'title' => 'Assessoria e Outsourcing de RH',
            'short' => 'Apoio sénior flexível para projectos, transformação ou operação contínua de RH e back office.',
            'value' => 'A assessoria externa dá capacidade técnica, velocidade e disciplina de execução sem aumentar estrutura fixa desnecessariamente.',
            'audience' => 'Empresas em crescimento, transformação ou com necessidade de reforço especializado em RH.',
            'alerts' => ['RH sobrecarregado por tarefas operacionais.', 'Projectos importantes sempre adiados.', 'Falta de experiência sénior interna para decisões críticas.', 'Back office sem processos claros.'],
            'checklist' => ['Que actividades devem ficar internas e quais podem ser apoiadas externamente?', 'Os processos críticos estão documentados?', 'Há indicadores de serviço?', 'A liderança recebe informação útil para decidir?'],
            'deliverables' => ['Plano de apoio mensal', 'Execução de processos de RH', 'Relatórios executivos', 'Transferência de capacidade para a equipa'],
        ],
        [
            'slug' => 'digitalizacao-rh-endomarketing',
            'title' => 'Digitalização de RH e Endomarketing',
            'short' => 'Processos digitais, adopção tecnológica e comunicação interna para melhorar a experiência do colaborador.',
            'value' => 'Digitalizar RH não é apenas trocar papel por sistema; é simplificar jornadas, melhorar dados e aproximar pessoas da cultura.',
            'audience' => 'Organizações que querem modernizar processos de RH, comunicação interna e experiência do colaborador.',
            'alerts' => ['Processos manuais repetitivos e lentos.', 'Informação dispersa em folhas, emails e pastas.', 'Baixa adesão a ferramentas digitais.', 'Comunicação interna fraca ou pouco segmentada.'],
            'checklist' => ['Quais processos podem ser simplificados antes de serem digitalizados?', 'A equipa compreende o valor da mudança?', 'Os dados de RH são fiáveis?', 'A comunicação interna apoia adopção e cultura?'],
            'deliverables' => ['Mapa de processos digitais', 'Plano de adopção tecnológica', 'Campanhas de endomarketing', 'Indicadores de experiência do colaborador'],
        ],
    ],
    'en' => [
        [
            'slug' => 'gestao-desempenho',
            'title' => 'Performance Management',
            'short' => 'Clear objectives, feedback, evaluation and development systems that turn effort into results.',
            'value' => 'A strong performance system creates focus, reduces subjectivity and helps leaders discuss results with evidence.',
            'audience' => 'Directors, HR leaders and management teams who want to align individual contribution with business priorities.',
            'alerts' => ['Objectives are unclear or change without criteria.', 'Performance conversations happen only at year-end.', 'Feedback is irregular or not actionable.', 'Weak connection between performance, development and rewards.'],
            'checklist' => ['Are individual objectives connected to company priorities?', 'Are feedback cycles regular and documented?', 'Do managers and employees understand the criteria?', 'Do results generate practical development plans?'],
            'deliverables' => ['Performance management model', 'Objectives and indicators matrix', 'Evaluation tools', 'Feedback and calibration guide'],
        ],
        [
            'slug' => 'carreira-sucessao',
            'title' => 'Career & Succession Planning',
            'short' => 'Career paths, succession maps and preparation of critical talent to ensure continuity.',
            'value' => 'Structured career and succession planning helps retain knowledge, prepare leaders and make growth visible.',
            'audience' => 'Organisations that want to reduce dependence on key people and make internal growth clearer.',
            'alerts' => ['Promotions happen without consistent criteria.', 'Critical talent has no development plan.', 'Leaders are prepared only when a vacancy appears.', 'Employees lack clarity on next steps.'],
            'checklist' => ['Are critical roles identified?', 'Is there a successor map by area?', 'Are progression criteria transparent?', 'Do potential successors have development plans?'],
            'deliverables' => ['Career architecture', 'Succession map', 'Progression criteria', 'Individual development plans'],
        ],
        [
            'slug' => 'avaliacao-classificacao-cargos',
            'title' => 'Job Evaluation & Classification',
            'short' => 'Job architecture, role descriptions and consistent grading for fair decisions.',
            'value' => 'Job evaluation creates a technical foundation for pay, structure, recruitment, development and expectation management.',
            'audience' => 'Companies that have grown, changed roles or need to organise responsibilities and levels with more rigour.',
            'alerts' => ['Roles overlap or duplicate responsibilities.', 'Different titles describe similar work.', 'Levels and salaries are hard to justify.', 'Job descriptions are outdated.'],
            'checklist' => ['Do job descriptions reflect real work?', 'Are responsibility levels clearly differentiated?', 'Are jobs classified with technical criteria?', 'Does the structure support pay and career decisions?'],
            'deliverables' => ['Job descriptions', 'Job evaluation matrix', 'Level structure', 'Classification report'],
        ],
        [
            'slug' => 'perfil-comportamental',
            'title' => 'Behavioural Profile Mapping',
            'short' => 'Evidence-based profiles to improve selection, team composition and individual development.',
            'value' => 'Understanding behavioural patterns improves decisions around hiring, leadership, teamwork and development.',
            'audience' => 'Teams that need to improve collaboration, recruitment, leadership or fit between people and roles.',
            'alerts' => ['Technically strong hires struggle with behavioural fit.', 'Recurring team conflict.', 'Managers struggle to adapt leadership styles.', 'Development plans are too generic.'],
            'checklist' => ['Are behavioural profiles used ethically and carefully?', 'Are role competencies well defined?', 'Does the team understand its work styles?', 'Do results translate into development actions?'],
            'deliverables' => ['Behavioural maps', 'Individual and team reports', 'Interview guides', 'Development recommendations'],
        ],
        [
            'slug' => 'recrutamento-seleccao',
            'title' => 'Recruitment & Selection',
            'short' => 'Rigorous recruitment processes aligned with role requirements, culture and business needs.',
            'value' => 'Good recruitment is not only filling vacancies; it reduces risk, accelerates onboarding and protects culture.',
            'audience' => 'Companies that need to attract, assess and select talent with consistency and responsible speed.',
            'alerts' => ['Hiring decisions rely only on CVs and informal interviews.', 'High turnover in the first months.', 'Long processes with poor communication.', 'Managers are misaligned on the ideal profile.'],
            'checklist' => ['Does the vacancy profile include technical and behavioural criteria?', 'Is screening evidence-based?', 'Are interviews structured?', 'Is there an onboarding plan after hiring?'],
            'deliverables' => ['Vacancy profile', 'Qualified shortlist', 'Assessment reports', 'Onboarding recommendations'],
        ],
        [
            'slug' => 'politicas-procedimentos',
            'title' => 'Policies & Procedures',
            'short' => 'Clear, practical HR policies and operating procedures aligned with compliance.',
            'value' => 'Good policies create predictability, protect the company and help managers decide fairly and consistently.',
            'audience' => 'Organisations that need to formalise rules, reduce improvisation and align internal practices.',
            'alerts' => ['Different decisions for similar cases.', 'Procedures known only by a few people.', 'Long documents nobody uses.', 'Legal risk due to unclear practices.'],
            'checklist' => ['Are policies updated and accessible?', 'Are procedures easy to execute?', 'Do managers know how to apply the rules?', 'Is there alignment between policy, law and culture?'],
            'deliverables' => ['HR policy manual', 'Procedure flows', 'Templates and forms', 'Implementation sessions'],
        ],
        [
            'slug' => 'remuneracao-beneficios',
            'title' => 'Compensation & Benefits',
            'short' => 'Pay and benefits models balanced between competitiveness, sustainability and internal equity.',
            'value' => 'A clear reward policy helps attract, retain and recognise talent without losing financial control.',
            'audience' => 'Companies that want to organise pay, benefits, bands and reward progression criteria.',
            'alerts' => ['Pay is defined through individual negotiation without structure.', 'Perceived internal unfairness.', 'Benefits are not valued by employees.', 'Difficulty retaining critical profiles.'],
            'checklist' => ['Is there a salary band structure?', 'Does the policy balance market and financial capacity?', 'Are review criteria clear?', 'Do benefits respond to employee needs?'],
            'deliverables' => ['Reward diagnosis', 'Salary bands', 'Benefits policy', 'Implementation recommendations'],
        ],
        [
            'slug' => 'formacao-desenvolvimento',
            'title' => 'Training & Development',
            'short' => 'Learning programmes designed around real capabilities, practical application and measurable impact.',
            'value' => 'Training creates value only when it starts from concrete needs and ends with visible change at work.',
            'audience' => 'Organisations that need to develop leadership, technical skills, communication, culture or performance.',
            'alerts' => ['Training is selected without diagnosis.', 'Participants are motivated on the day but do not apply learning.', 'No learning indicators.', 'Development plans are weakly connected to the business.'],
            'checklist' => ['Is the training need well diagnosed?', 'Are learning objectives measurable?', 'Is there practical application after training?', 'Do managers follow up on impact?'],
            'deliverables' => ['Needs diagnosis', 'Training plan', 'Learning materials', 'Impact evaluation'],
        ],
        [
            'slug' => 'assessoria-outsourcing-rh',
            'title' => 'HR Advisory & Outsourcing',
            'short' => 'Flexible senior support for HR projects, transformation or ongoing people operations.',
            'value' => 'External advisory brings technical depth, speed and execution discipline without unnecessary fixed structure.',
            'audience' => 'Growing or transforming companies that need specialised HR capacity.',
            'alerts' => ['HR is overloaded with operational tasks.', 'Important projects are constantly delayed.', 'Internal senior experience is missing for critical decisions.', 'Back-office processes are unclear.'],
            'checklist' => ['Which activities should remain internal and which can be externally supported?', 'Are critical processes documented?', 'Are service indicators defined?', 'Does leadership receive useful information for decisions?'],
            'deliverables' => ['Monthly support plan', 'Execution of HR processes', 'Executive reports', 'Capability transfer to the internal team'],
        ],
        [
            'slug' => 'digitalizacao-rh-endomarketing',
            'title' => 'HR Digitalisation & Internal Branding',
            'short' => 'Digital processes, technology adoption and internal communication to improve employee experience.',
            'value' => 'Digitalising HR is not just replacing paper with systems; it simplifies journeys, improves data and strengthens culture.',
            'audience' => 'Organisations that want to modernise HR processes, internal communication and employee experience.',
            'alerts' => ['Manual, repetitive and slow processes.', 'Information scattered across spreadsheets, emails and folders.', 'Low adoption of digital tools.', 'Weak or poorly segmented internal communication.'],
            'checklist' => ['Which processes should be simplified before being digitalised?', 'Does the team understand the value of the change?', 'Is HR data reliable?', 'Does internal communication support adoption and culture?'],
            'deliverables' => ['Digital process map', 'Technology adoption plan', 'Internal branding campaigns', 'Employee experience indicators'],
        ],
    ],
];
