@extends('layouts.app')
@section('title', $locale === 'en' ? 'About us' : 'Sobre nós')
@section('description', $locale === 'en' ? 'Meet Business Diversity, our purpose, values and consulting team.' : 'Conheça a Business Diversity, o nosso propósito, valores e equipa de consultoria.')

@section('content')
@php($en = $locale === 'en')
<section class="page-hero inner-hero inner-hero-about"><div class="container inner-hero-grid">
    <div class="inner-hero-copy"><span class="eyebrow light">{{ $en ? 'ABOUT BUSINESS DIVERSITY' : 'SOBRE A BUSINESS DIVERSITY' }}</span><h1>{{ $en ? 'Local insight. Senior expertise. Practical results.' : 'Conhecimento local. Experiência sénior. Resultados práticos.' }}</h1><p>{{ $en ? 'For more than eight years, we have helped organisations grow through better people decisions.' : 'Há mais de oito anos ajudamos organizações a crescer através de melhores decisões sobre pessoas.' }}</p></div>
    <div class="inner-hero-cards credential-cards" aria-label="{{ $en ? 'Business Diversity credentials' : 'Credenciais da Business Diversity' }}">
        <article class="inner-data-card card-bright"><span>{{ $en ? 'TRUST BUILT' : 'CONFIANÇA CONSTRUÍDA' }}</span><strong>8+</strong><small>{{ $en ? 'years in the market' : 'anos no mercado' }}</small></article>
        <article class="inner-data-card"><span>{{ $en ? 'EXPERIENCE THAT GUIDES' : 'EXPERIÊNCIA QUE ORIENTA' }}</span><strong>22+</strong><small>{{ $en ? 'years brought by senior professionals' : 'anos trazidos por profissionais séniores' }}</small></article>
        <article class="inner-principle-card"><i>↗</i><p>{{ $en ? 'Young talent brings digitalisation, internal branding, technology and new perspectives.' : 'Talentos jovens acrescentam digitalização, endomarketing, tecnologia e novas perspectivas.' }}</p></article>
    </div>
</div></section>

<section class="section"><div class="container story-grid"><div><span class="eyebrow">{{ $en ? 'OUR STORY' : 'A NOSSA HISTÓRIA' }}</span><h2>{{ $en ? 'We work beside our clients, not at a distance.' : 'Trabalhamos ao lado dos nossos clientes, não à distância.' }}</h2></div><div><p class="lead">{{ $en ? 'Business Diversity helps organisations focus on their core business while strengthening the people and back-office operations that sustain growth.' : 'A Business Diversity ajuda organizações a concentrarem-se no seu negócio principal, enquanto fortalece as pessoas e as operações de back office que sustentam o crescimento.' }}</p><p>{{ $en ? 'Our work is grounded in senior human resources experience, local context and a strong belief that every solution must be useful in practice.' : 'O nosso trabalho assenta em experiência sénior de recursos humanos, conhecimento do contexto local e na convicção de que cada solução deve ser útil na prática.' }}</p></div></div></section>

<section class="section purpose-section"><div class="container purpose-grid"><article><span>01</span><h2>{{ $en ? 'Vision' : 'Visão' }}</h2><p>{{ $en ? 'To be the preferred partner for organisations that value people and sustainable performance.' : 'Ser o parceiro de preferência das organizações que valorizam pessoas e desempenho sustentável.' }}</p></article><article><span>02</span><h2>{{ $en ? 'Mission' : 'Missão' }}</h2><p>{{ $en ? 'To help our partners focus on their core business while we strengthen their human capital and back-office operations.' : 'Ajudar os nossos parceiros a concentrarem-se no seu negócio principal, enquanto fortalecemos o seu capital humano e operações de back office.' }}</p></article><article><span>03</span><h2>{{ $en ? 'Values' : 'Valores' }}</h2><p>{{ $en ? 'Integrity, partnership, excellence, inclusion and a practical commitment to results.' : 'Integridade, parceria, excelência, inclusão e compromisso prático com resultados.' }}</p></article></div></section>

<section class="section team-section"><div class="container"><div class="section-header"><div><span class="eyebrow">{{ $en ? 'OUR TEAM' : 'A NOSSA EQUIPA' }}</span><h2>{{ $en ? 'Experience that guides. Talent that innovates.' : 'Experiência que orienta. Talento que inova.' }}</h2></div><p>{{ $en ? 'Senior professionals work alongside a young, multidisciplinary team connected to digitalisation, communication and technology.' : 'Profissionais séniores trabalham com uma equipa jovem e multidisciplinar, ligada à digitalização, comunicação e tecnologia.' }}</p></div><div class="team-grid">
    <article class="team-card"><img src="{{ asset('assets/images/team-sandra-v2.png') }}" alt="Sandra Nhachale" loading="lazy"><div><h3>Sandra Nhachale</h3><span>{{ $en ? 'Managing Director' : 'Directora Geral' }}</span><p>{{ $en ? 'Senior professional with over 22 years of experience and a solid foundation in human resources.' : 'Profissional sénior com mais de 22 anos de experiência e bases sólidas em Recursos Humanos.' }}</p></div></article>
    <article class="team-card"><img src="{{ asset('assets/images/team-luis-v2.png') }}" alt="Luís Sitoe" loading="lazy"><div><h3>Luís Sitoe</h3><span>{{ $en ? 'Communication Consultant' : 'Consultor de Comunicação' }}</span><p>{{ $en ? 'Communication expertise applied to stronger organisations and meaningful stakeholder relationships.' : 'Experiência em comunicação aplicada a organizações mais fortes e relações relevantes com stakeholders.' }}</p></div></article>
    <article class="team-card"><img src="{{ asset('assets/images/team-shelzer-v2.png') }}" alt="Shelzer Tembe" loading="lazy"><div><h3>Shelzer Tembe</h3><span>{{ $en ? 'Research & Optimisation' : 'Estudos e Optimização' }}</span><p>{{ $en ? 'Integrates technology and human resources strategies into effective, comprehensive solutions.' : 'Integra tecnologia e estratégias de Recursos Humanos em soluções eficazes e abrangentes.' }}</p></div></article>
</div></div></section>
@endsection
